name: EAS Build and Update

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "You must set an EXPO_TOKEN secret in your repository's settings."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ env.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: eas build --platform all --profile production --non-interactive

      - name: Publish update
        run: eas update --auto --non-interactive
